name: Upload tag to GitHub

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/elgohr/publish-docker-github-action/publish-docker-github-action
          username: "Orta"
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
