name: Upload tag to GitHub

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/elgohr/danger/danger-js/release
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com


        - name: Push
          run: |
            docker login docker.pkg.github.com --username RepoOwner --password "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
            docker push docker.pkg.github.com/danger/danger-js/master:tag
          env:
            GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

